# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 178)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_play = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_play.setFont(font)
        self.pushButton_play.setAutoDefault(False)
        self.pushButton_play.setObjectName("pushButton_play")
        self.verticalLayout.addWidget(self.pushButton_play)
        self.lineEdit_read_symbol = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_read_symbol.setObjectName("lineEdit_read_symbol")
        self.verticalLayout.addWidget(self.lineEdit_read_symbol)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_dot = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_dot.setAutoFillBackground(False)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.horizontalLayout.addWidget(self.pushButton_dot)
        self.pushButton_dash = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_dash.setFont(font)
        self.pushButton_dash.setAutoDefault(False)
        self.pushButton_dash.setObjectName("pushButton_dash")
        self.horizontalLayout.addWidget(self.pushButton_dash)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Morse CODE"))
        self.pushButton_play.setText(_translate("MainWindow", "Play"))
        self.pushButton_dot.setText(_translate("MainWindow", "Dot"))
        self.pushButton_dash.setText(_translate("MainWindow", "Dash"))
